#!/bin/sh
[ "$(uci -q get system.@system[0].init)" != "" ] && exit 0
#set lan ip
uci set network.lan.ipaddr='192.168.10.1'
uci commit network

uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].cronloglevel='8'
uci set system.@system[0].conloglevel='7'
uci set system.@system[0].init='initiated'
uci commit system

#set luci default language
uci set luci.main.lang='zh_cn'
uci commit luci

#enable flow offloading
uci set firewall.@defaults[0].flow_offloading='1'
uci commit firewall

uci set passwall.@global_subscribe[0].trojan_type='v2ray'
uci del passwall.@global_rules[0].gfwlist_url
uci add_list passwall.@global_rules[0].gfwlist_url='https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt'
uci add_list passwall.@global_rules[0].gfwlist_url='https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/greatfire.txt'
uci set passwall.@global[0].tcp_proxy_mode='gfwlist'
uci set passwall.@global[0].udp_proxy_mode='disable'
uci commit passwall

#edit feeds
sed -i 's/downloads.openwrt.org/mirrors.ustc.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
echo 'src/gz custom https://drive.939.me/api/raw/?path=/Openwrt/Package/x86-64' >> /etc/opkg/customfeeds.conf