#!/bin/sh

#edit feeds
sed -i 's/downloads.openwrt.org/mirrors.ustc.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
[ "$(grep "custom" /etc/opkg/distfeeds.conf)" == "" ] && echo 'src/gz custom https://drive.939.me/api/raw/?path=/Openwrt/Package/22.03.3/x86-64' >> /etc/opkg/distfeeds.conf

[ "$(uci -q get system.@system[0].init)" != "" ] && exit 0
#set lan ip
uci set network.lan.ipaddr='192.168.10.1'
uci commit network

uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].cronloglevel='8'
uci set system.@system[0].conloglevel='7'
uci set system.@system[0].init='initiated'
uci commit system

#set luci default language
uci set luci.main.lang='zh_cn'
uci commit luci

#enable flow offloading
uci set firewall.@defaults[0].flow_offloading='1'
uci commit firewall
